import type { UiPackageManifest } from '@gluonjs/quarks';

const sharedEvidence = {
  example: 'docs-site/examples/ui-system.ts',
  tests: ['tests/ui-system.spec.ts', 'tests/ui-visual.spec.ts'],
} as const;

export const moleculeManifest = Object.freeze({
  schemaVersion: 1,
  package: '@gluonjs/molecules',
  layer: 'molecule',
  entries: Object.freeze([
    { name: 'Accordion', kind: 'component', status: 'stable', styles: ['gluon-molecule-accordion'], accessibility: 'Composes native Disclosure details and summary controls inside a named group with stable IDs, controlled single or multiple open values, heading levels, optional Arrow/Home/End focus movement, unavailable skipping, and unchanged Tab order.', extension: 'attributes target the outer HTMLDivElement; callers own items, content loading, controlled values, collapse policy, unavailable reasons, and change effects.', ...sharedEvidence },
    { name: 'ButtonGroup', kind: 'component', status: 'stable', styles: ['gluon-molecule-button-group'], accessibility: 'Renders a named role=group around caller-owned native Button or ToggleButton controls while preserving source order, Tab order, and each child semantic.', extension: 'attributes targets HTMLDivElement; accessible label, orientation, attached or spaced layout, wrapping, and child controls stay explicit without selection, routing, menu, or pressed-state ownership.', ...sharedEvidence },
    { name: 'Card', kind: 'component', status: 'stable', styles: ['gluon-molecule-card'], accessibility: 'Renders a native article with optional heading content; callers preserve heading level order around repeated cards.', extension: 'attributes targets HTMLElement article; title, media, actions, and body children stay explicit.', ...sharedEvidence },
    { name: 'ChoiceGroup', kind: 'component', status: 'stable', styles: ['gluon-molecule-choice-group'], accessibility: 'Renders a native fieldset and visible legend with optional helper, announced error, disabled propagation, and native Checkbox or Radio keyboard/form behavior.', extension: 'attributes targets HTMLFieldSetElement; legend, option controls, values, checked state, copy, validation, and vertical or horizontal layout stay explicit.', ...sharedEvidence },
    { name: 'ControlField', kind: 'component', status: 'stable', styles: ['gluon-molecule-control-field'], accessibility: 'Provides a visible native label plus deterministic label, helper, error, required-indicator, aria-describedby, aria-errormessage, and aria-invalid relationships for a caller-rendered control.', extension: 'attributes targets the outer HTMLDivElement; a render callback receives public relationship metadata while control value, events, validation, and native attributes stay caller-owned.', ...sharedEvidence },
    { name: 'DialogSurface', kind: 'component', status: 'stable', styles: ['gluon-molecule-dialog-surface'], accessibility: 'Composes the ARIA Dialog and Overlay quarks with an explicit accessible name, Escape and overlay dismissal, a focus-scope controller for initial, contained, and return focus, optional description, and structured header, content, and footer regions.', extension: 'Callers own open state, close action, title and copy, async and destructive decisions, native attributes, and controller lifecycle; this ARIA surface does not invoke the native dialog top layer.', ...sharedEvidence },
    { name: 'Disclosure', kind: 'component', status: 'stable', styles: ['gluon-molecule-disclosure'], accessibility: 'Preserves native details and summary semantics, keyboard toggling, find-in-page expansion, open state, and toggle events; unavailable summaries remain focusable, expose aria-disabled and a visible reason, and prevent activation.', extension: 'attributes target HTMLDetailsElement; summaryAttributes target the native summary; callers own controlled or initial open state, content, toggle effects, and unavailable reasons.', ...sharedEvidence },
    { name: 'ResponsiveDisclosure', kind: 'component', status: 'stable', styles: ['gluon-molecule-disclosure'], accessibility: 'Uses one native details/summary tree, keeps desktop expanded, restores the last compact user choice across breakpoint changes, synchronizes aria-expanded, and removes its MediaQueryList listener on disconnect.', extension: 'compactBreakpoint and compactInitialOpen define compact state; compactResetToken is the deliberate reset boundary; callers own content and effects.', ...sharedEvidence },
    { name: 'EmptyState', kind: 'component', status: 'stable', styles: ['gluon-molecule-empty-state'], accessibility: 'Renders optional media, a semantic heading level, body, and recovery action as static content without repeatedly announcing an unchanged empty state; dynamic feedback belongs in a separate live region.', extension: 'attributes target the outer HTMLDivElement; callers own copy, media semantics, recovery controls, routes, loading, analytics, live feedback, and compact or full presentation.', ...sharedEvidence },
    { name: 'FormField', kind: 'component', status: 'stable', styles: ['gluon-molecule-form-field'], accessibility: 'Uses implicit native label association, visible helper text, aria-invalid, and a role=alert validation message.', extension: 'Input attributes target HTMLInputElement; fieldAttributes targets HTMLLabelElement; composed children stay explicit.', ...sharedEvidence },
    { name: 'InlineNotice', kind: 'component', status: 'stable', styles: ['gluon-molecule-inline-notice'], accessibility: 'Renders bounded feedback with a non-color marker and deliberate auto, polite status, assertive alert, or static off announcement semantics while keeping optional actions outside the live region.', extension: 'attributes target the outer HTMLDivElement; callers own copy, title, action and dismiss controls, announcement timing, message lifecycle, and effects.', ...sharedEvidence },
    { name: 'NavigationStrip', kind: 'component', status: 'stable', styles: ['gluon-molecule-navigation-strip'], accessibility: 'Renders a named native navigation landmark, exposes keyboard-operable overflow controls, and reveals the exact aria-current destination.', extension: 'attributes targets the native navigation landmark; destination markup and active-state semantics stay caller-owned.', ...sharedEvidence },
    { name: 'ResponsiveActionBar', kind: 'component', status: 'stable', styles: ['gluon-molecule-responsive-action-bar'], accessibility: 'Renders one semantic section with one caller-owned primary action instance, an optional compact control, native busy/disabled metadata, and one bounded status live region using only aria-live=polite or assertive; sticky mobile layout remains in normal flow and becomes inline at wider widths.', extension: 'summary, status, primaryAction, compactControl, state, presentation, and application-owned labels/effects stay caller-owned. Invalid state or presentation values fail closed. Safe-area padding, logical sizing, short-viewport static fallback, forced colors, reduced motion, and 44px action targets are component-owned.', ...sharedEvidence },
    { name: 'DropdownMenu', kind: 'component', status: 'stable', styles: ['gluon-molecule-menu-toolbar'], accessibility: 'Provides one roving Tab stop, buffered typeahead, disabled skipping, separators, checkbox/radio roles, controlled nested submenus, Escape/focus return, and RTL movement from a keyboard-complete menu button.', extension: 'A collision-safe instance ID, item data, links, buttons, selection effects, checked state, submenu state, and controlled root open state remain caller-owned.', ...sharedEvidence },
    { name: 'ContextMenu', kind: 'component', status: 'stable', styles: ['gluon-molecule-menu-toolbar'], accessibility: 'Supports pointer, ContextMenu-key, and Shift+F10 invocation without a synthetic trigger; opening focuses the menu and Escape returns focus to the native target surface.', extension: 'Target content, instance ID, position gesture, controlled open state, item effects, routing, commands, and authorization remain caller-owned.', ...sharedEvidence },
    { name: 'Menubar', kind: 'component', status: 'stable', styles: ['gluon-molecule-menu-toolbar'], accessibility: 'Renders an APG menubar with direct top-level menuitem semantics, one roving Tab stop, buffered typeahead, orientation/RTL movement, controlled nested submenus, and Escape focus behavior.', extension: 'Items, links, checked/submenu state, effects, routing, authorization, and command execution remain caller-owned.', ...sharedEvidence },
    { name: 'Toolbar', kind: 'component', status: 'stable', styles: ['gluon-molecule-toolbar'], accessibility: 'Renders a named toolbar of native buttons and links with one enabled Tab stop, disabled skipping, Home/End, and orientation/RTL Arrow movement.', extension: 'The bounded item model preserves caller attributes and native activation while actions, links, labels, authorization, and command execution remain caller-owned.', ...sharedEvidence },
    { name: 'SegmentedControl', kind: 'component', status: 'stable', styles: ['gluon-molecule-segmented-control'], accessibility: 'Renders a named toolbar of native toggle buttons with one controlled aria-pressed value, one Tab stop, disabled-option skipping, Arrow/Home/End navigation, RTL, and horizontal or vertical orientation.', extension: 'attributes targets HTMLDivElement; caller owns value, options, labels, disabled states, change handling, routing, persistence, panels, and async work; it is not a tablist or radiogroup.', ...sharedEvidence },
    { name: 'TableRegion', kind: 'component', status: 'stable', styles: ['gluon-molecule-table-region'], accessibility: 'Wraps a caller-owned native table in a named region, preserves table semantics and source order, exposes optional summary and overflow hint relationships, and adds one viewport Tab stop only while horizontal overflow exists.', extension: 'attributes target the outer HTMLDivElement; callers own table markup, caption and headers, columns, rows, sorting, pagination, virtualization, selection, editing, empty content, data, and effects; it is not a DataGrid.', ...sharedEvidence },
    { name: 'Tabs', kind: 'component', status: 'stable', styles: ['gluon-molecule-tabs'], accessibility: 'Implements a labelled WAI-ARIA tablist with stable tab/panel IDs, controlled selection, one Tab stop, disabled skipping, Arrow/Home/End navigation, manual or automatic activation, orientation, RTL, and focus retention.', extension: 'attributes targets the outer HTMLDivElement; callers own tab labels, panel content, value, loading, routing, persistence, and change effects.', ...sharedEvidence },
    { name: 'SearchField', kind: 'component', status: 'stable', styles: ['gluon-molecule-search-field'], accessibility: 'Renders a native labelled search input inside a role=search form with a submit button, stable caller-owned DOM IDs, controlled query value, disabled state, and stable busy indication.', extension: 'The component is request-free; IDs, names, and labels fail closed when empty or structurally invalid, native listener objects/functions compose before the controlled callbacks, and callers own query state, submission, network, ranking, routing, authorization, and analytics.', ...sharedEvidence },
    { name: 'SearchResults', kind: 'component', status: 'stable', styles: ['gluon-molecule-search-results'], accessibility: 'Renders grouped native sections with instance-namespaced headings, optional descriptions and counts, an unordered result list, and explicit loading, empty, partial-failure, and disabled states; partial failures retain available groups and announce their caller-localized content through one polite status.', extension: 'Results are render-only TemplateValues; structurally valid DOM IDs, unique per-instance group IDs, states, and heading levels fail closed, while callers own result links, fetching, ranking, authorization, routing, and live-region timing beyond the component status.', ...sharedEvidence },
  ]),
} as const satisfies UiPackageManifest);
