#!/usr/bin/env node

import { constants, realpathSync } from 'node:fs';
import { access, readFile, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const templatePath = resolve(packageRoot, 'agent-skill', 'SKILL.template.md');
const generatedMarker = '<!-- Generated by @gluonjs/core. Run `gluon-skill --regenerate` to refresh. -->';

function isEnabled(value) {
  return !['', '0', 'false', 'no', 'off'].includes(String(value ?? '').trim().toLowerCase());
}

async function isProjectRoot(directory) {
  try {
    const packageJson = JSON.parse(await readFile(resolve(directory, 'package.json'), 'utf8'));
    return packageJson !== null && typeof packageJson === 'object';
  } catch {
    return false;
  }
}

export async function resolveProjectRoot({
  cwd = process.cwd(),
  env = process.env,
  explicitRoot,
} = {}) {
  if (explicitRoot) {
    const root = resolve(cwd, explicitRoot);
    if (!(await isProjectRoot(root))) {
      throw new Error(`Project root has no package.json: ${root}`);
    }
    return root;
  }

  const candidates = [env.INIT_CWD, env.PROJECT_CWD, env.npm_config_local_prefix, cwd]
    .filter(Boolean)
    .map((candidate) => resolve(candidate));

  for (const candidate of candidates) {
    let current = candidate;
    while (true) {
      if (await isProjectRoot(current)) return current;
      const parent = dirname(current);
      if (parent === current) break;
      current = parent;
    }
  }

  throw new Error('Could not find an installing project root with package.json.');
}

export async function installAgentSkill({
  cwd,
  env = process.env,
  explicitRoot,
  regenerate = false,
} = {}) {
  if (isEnabled(env.GLUON_SKIP_AGENT_SKILL)) {
    return { status: 'skipped', reason: 'opt-out' };
  }

  const projectRoot = await resolveProjectRoot({ cwd, env, explicitRoot });
  const destination = resolve(projectRoot, 'SKILL.md');
  const destinationRelative = relative(projectRoot, destination);
  if (destinationRelative.startsWith('..') || resolve(destination) === resolve(projectRoot)) {
    throw new Error(`Refusing unsafe skill destination: ${destination}`);
  }

  // Installing dependencies in the Gluon source checkout must not modify it.
  if (resolve(projectRoot) === packageRoot) {
    return { status: 'skipped', reason: 'package-source', path: destination };
  }

  let existing;
  try {
    existing = await readFile(destination, 'utf8');
  } catch (error) {
    if (error?.code !== 'ENOENT') throw error;
  }

  if (existing !== undefined) {
    if (!regenerate) return { status: 'unchanged', reason: 'existing', path: destination };
    if (!existing.startsWith(generatedMarker)) {
      return { status: 'unchanged', reason: 'user-owned', path: destination };
    }
  }

  await access(projectRoot, constants.W_OK);
  const template = await readFile(templatePath, 'utf8');
  await writeFile(destination, `${generatedMarker}\n${template}`, {
    encoding: 'utf8',
    flag: existing === undefined ? 'wx' : 'w',
  });
  return { status: existing === undefined ? 'created' : 'regenerated', path: destination };
}

function parseArguments(argv) {
  const options = { regenerate: false };
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === '--regenerate') options.regenerate = true;
    else if (argument === '--root' && argv[index + 1]) options.explicitRoot = argv[++index];
    else if (argument === '--help' || argument === '-h') options.help = true;
    else throw new Error(`Unknown argument: ${argument}`);
  }
  return options;
}

export async function run(argv = process.argv.slice(2), context = {}) {
  const options = parseArguments(argv);
  if (options.help) {
    console.log(`Usage: gluon-skill [--root <project>] [--regenerate]

Creates SKILL.md when absent. --regenerate only replaces a file previously
generated by @gluonjs/core. Set GLUON_SKIP_AGENT_SKILL=1 to opt out.`);
    return 0;
  }

  const result = await installAgentSkill({ ...context, ...options });
  if (result.status === 'created' || result.status === 'regenerated') {
    console.log(`Gluon agent skill ${result.status}: ${result.path}`);
  } else if (result.reason === 'user-owned') {
    console.warn(`Gluon agent skill not replaced because ${result.path} is user-owned.`);
  }
  return 0;
}

if (
  process.argv[1]
  && realpathSync(resolve(process.argv[1])) === realpathSync(fileURLToPath(import.meta.url))
) {
  run().catch((error) => {
    // Dependency installation must stay usable in read-only or unusual workspace
    // layouts. The explicit CLI reports the same warning and can be retried.
    console.warn(`Gluon agent skill was not installed: ${error.message}`);
    process.exitCode = 0;
  });
}
