import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, resolve } from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

import { installAgentSkill, resolveProjectRoot } from '../agent-skill/install.mjs';

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const marker = '<!-- Generated by @gluonjs/core. Run `gluon-skill --regenerate` to refresh. -->';

async function project(name = 'consumer') {
  const root = await mkdtemp(resolve(tmpdir(), 'gluon-agent-skill-'));
  await writeFile(resolve(root, 'package.json'), JSON.stringify({ name, private: true }));
  return root;
}

test('resolves npm, pnpm, and Yarn lifecycle roots before the package cwd', async () => {
  for (const key of ['INIT_CWD', 'PROJECT_CWD', 'npm_config_local_prefix']) {
    const root = await project(key.toLowerCase());
    const packageCwd = resolve(root, 'node_modules', '@gluonjs', 'core');
    await mkdir(packageCwd, { recursive: true });
    await writeFile(resolve(packageCwd, 'package.json'), JSON.stringify({ name: '@gluonjs/core' }));
    assert.equal(await resolveProjectRoot({ cwd: packageCwd, env: { [key]: root } }), root);
  }
});

test('creates once, preserves every existing file, and only regenerates marked output', async () => {
  const root = await project();
  const created = await installAgentSkill({ cwd: root, env: {} });
  assert.equal(created.status, 'created');
  const generated = await readFile(resolve(root, 'SKILL.md'), 'utf8');
  assert.match(generated, /^<!-- Generated by @gluonjs\/core/);
  for (const packageName of [
    '@gluonjs/quarks',
    '@gluonjs/atoms',
    '@gluonjs/molecules',
    '@gluonjs/organisms',
    '@gluonjs/vite',
    '@gluonjs/gluon-components-vite',
  ]) {
    assert.match(generated, new RegExp(packageName.replace('/', '\\/')));
  }

  assert.equal((await installAgentSkill({ cwd: root, env: {} })).status, 'unchanged');
  assert.equal(await readFile(resolve(root, 'SKILL.md'), 'utf8'), generated);

  await writeFile(resolve(root, 'SKILL.md'), '# Mine\n');
  const protectedResult = await installAgentSkill({ cwd: root, env: {}, regenerate: true });
  assert.equal(protectedResult.reason, 'user-owned');
  assert.equal(await readFile(resolve(root, 'SKILL.md'), 'utf8'), '# Mine\n');

  await writeFile(resolve(root, 'SKILL.md'), `${marker} edited\n`);
  assert.equal(
    (await installAgentSkill({ cwd: root, env: {}, regenerate: true })).status,
    'regenerated',
  );
  assert.match(await readFile(resolve(root, 'SKILL.md'), 'utf8'), /^<!-- Generated by @gluonjs\/core/);
});

test('supports opt-out and rejects an explicit directory without package.json', async () => {
  const root = await project();
  assert.deepEqual(
    await installAgentSkill({ cwd: root, env: { GLUON_SKIP_AGENT_SKILL: '1' } }),
    { status: 'skipped', reason: 'opt-out' },
  );
  await assert.rejects(
    resolveProjectRoot({ cwd: root, env: {}, explicitRoot: 'missing' }),
    /has no package\.json/,
  );
});

test('packed core contains the installer and works in a consumer after scripts were ignored', {
  timeout: 120_000,
}, async () => {
  const packDirectory = await mkdtemp(resolve(tmpdir(), 'gluon-core-pack-'));
  const npmCache = resolve(packDirectory, 'npm-cache');
  await mkdir(npmCache);
  const stdout = execFileSync(
    'npm',
    ['pack', '--json', '--ignore-scripts', '--pack-destination', packDirectory],
    {
      cwd: repositoryRoot,
      encoding: 'utf8',
      env: { ...process.env, npm_config_cache: npmCache },
      timeout: 20_000,
    },
  );
  const pack = JSON.parse(stdout)[0];
  const paths = new Set(pack.files.map((file) => file.path));
  assert(paths.has('agent-skill/install.mjs'));
  assert(paths.has('agent-skill/SKILL.template.md'));

  const root = await project('packed-consumer');
  const unpacked = resolve(root, 'node_modules', '@gluonjs', 'core');
  await mkdir(dirname(unpacked), { recursive: true });
  execFileSync('tar', ['-xzf', resolve(packDirectory, pack.filename), '-C', dirname(unpacked)], {
    timeout: 10_000,
  });
  execFileSync('mv', [resolve(dirname(unpacked), 'package'), unpacked], { timeout: 10_000 });

  await assert.rejects(stat(resolve(root, 'SKILL.md')), { code: 'ENOENT' });
  const installStdout = execFileSync('node', [
    resolve(unpacked, 'agent-skill', 'install.mjs'),
  ], {
    cwd: root,
    encoding: 'utf8',
    timeout: 10_000,
    env: {
      ...process.env,
      INIT_CWD: root,
      PROJECT_CWD: root,
      npm_config_local_prefix: root,
    },
  });
  assert.match(installStdout, /Gluon agent skill created:/);
  const skill = await readFile(resolve(root, 'SKILL.md'), 'utf8');
  assert.match(skill, /^<!-- Generated by @gluonjs\/core/);
  assert.match(skill, /## Storybook/);
});
