import type { UiPackageManifest } from '@gluonjs/quarks';

const sharedEvidence = {
  example: 'docs-site/examples/ui-system.ts',
  tests: ['tests/ui-system.spec.ts', 'tests/ui-visual.spec.ts'],
} as const;

export const atomManifest = Object.freeze({
  schemaVersion: 1,
  package: '@gluonjs/atoms',
  layer: 'atom',
  entries: Object.freeze([
    { name: 'AspectRatio', kind: 'component', status: 'stable', styles: ['gluon-atom-aspect-ratio'], variants: ['16:9', '1:1', '4:3'], states: ['default'], preview: 'aspect-ratio', accessibility: 'Renders a native div without adding semantics; positive finite ratio validation prevents invalid geometry.', extension: 'attributes targets HTMLDivElement; ratio maps to --gluon-aspect-ratio and caller classes/styles merge safely.', ...sharedEvidence },
    { name: 'Heading', kind: 'component', status: 'stable', styles: ['gluon-atom-foundation'], variants: ['level-1', 'level-2', 'level-3', 'level-4', 'level-5', 'level-6'], states: ['default', 'focusable'], preview: 'foundation-atoms--typography', accessibility: 'Renders one native h1-h6 element with caller-owned heading hierarchy and no duplicate landmark semantics.', extension: 'level selects the native heading tag; attributes target the heading and children remain explicit.', ...sharedEvidence },
    { name: 'Text', kind: 'component', status: 'stable', styles: ['gluon-atom-foundation'], variants: ['paragraph', 'span', 'muted', 'danger'], states: ['default'], preview: 'foundation-atoms--typography', accessibility: 'Renders caller-selected native paragraph, span, or div content without inventing a role or live-region announcement.', extension: 'as and tone control presentation while native attributes and content remain caller-owned.', ...sharedEvidence },
    { name: 'Link', kind: 'component', status: 'stable', styles: ['gluon-atom-foundation'], variants: ['default', 'external'], states: ['default', 'focus-visible'], preview: 'foundation-atoms--link', accessibility: 'Renders a native anchor when href is supplied and preserves browser navigation, keyboard, focus, and visited semantics.', extension: 'href and native anchor attributes remain explicit; routing and authorization stay caller-owned.', ...sharedEvidence },
    { name: 'Image', kind: 'component', status: 'stable', styles: ['gluon-atom-foundation'], variants: ['responsive', 'intrinsic'], states: ['loading', 'loaded', 'error'], preview: 'foundation-atoms--media', accessibility: 'Renders one native image with required alternative text and caller-owned loading/error policy.', extension: 'src, alt, dimensions, loading, decoding, and native image attributes remain explicit; fetching and fallback content stay caller-owned.', ...sharedEvidence },
    { name: 'Badge', kind: 'component', status: 'stable', styles: ['gluon-atom-foundation'], variants: ['neutral', 'info', 'success', 'warning', 'danger'], states: ['default'], preview: 'foundation-atoms--badge', accessibility: 'Renders a presentational status token without assuming live-region semantics or relying on color alone.', extension: 'tone selects presentation; callers own text, semantics, and domain mapping.', ...sharedEvidence },
    { name: 'Spinner', kind: 'component', status: 'stable', styles: ['gluon-atom-foundation'], variants: ['inline'], states: ['loading'], preview: 'foundation-atoms--feedback', accessibility: 'Renders one labelled status indicator; reduced motion disables the rotation animation.', extension: 'label and native span attributes remain explicit; request lifecycle and cancellation stay caller-owned.', ...sharedEvidence },
    { name: 'Skeleton', kind: 'component', status: 'stable', styles: ['gluon-atom-foundation'], variants: ['text', 'block'], states: ['loading'], preview: 'foundation-atoms--feedback', accessibility: 'Renders an aria-hidden loading placeholder that does not announce duplicate progress.', extension: 'width and height are CSS-variable-backed presentation hints; loaded content and timing remain caller-owned.', ...sharedEvidence },
    { name: 'Meter', kind: 'component', status: 'stable', styles: ['gluon-atom-foundation'], variants: ['default'], states: ['determinate'], preview: 'foundation-atoms--feedback', accessibility: 'Renders the native meter element; callers provide its accessible name and truthful min/max/value semantics.', extension: 'Value, range, children, and native attributes stay explicit without owning domain thresholds.', ...sharedEvidence },
    { name: 'NumberInput', kind: 'component', status: 'stable', styles: ['gluon-atom-input'], variants: ['default'], states: ['default', 'disabled', 'invalid'], preview: 'foundation-atoms--numeric-input', accessibility: 'Renders a native number input with browser editing, validation, keyboard, and form semantics.', extension: 'Uses the public Input contract with a fixed native number type; callers own min/max/step through attributes.', ...sharedEvidence },
    { name: 'DateInput', kind: 'component', status: 'stable', styles: ['gluon-atom-input'], variants: ['default'], states: ['default', 'disabled', 'invalid'], preview: 'foundation-atoms--date-input', accessibility: 'Renders a native date input and preserves platform date-picker, keyboard, validation, and form behavior.', extension: 'Uses the public Input contract with a fixed native date type; locale and timezone policy stay caller-owned.', ...sharedEvidence },
    { name: 'TimeInput', kind: 'component', status: 'stable', styles: ['gluon-atom-input'], variants: ['default'], states: ['default', 'disabled', 'invalid'], preview: 'foundation-atoms--time-input', accessibility: 'Renders a native time input and preserves platform time-picker, keyboard, validation, and form behavior.', extension: 'Uses the public Input contract with a fixed native time type; timezone and business-hours policy stay caller-owned.', ...sharedEvidence },
    { name: 'FileInput', kind: 'component', status: 'stable', styles: ['gluon-atom-file-input'], variants: ['single', 'multiple', 'capture'], states: ['default', 'disabled', 'invalid'], preview: 'foundation-atoms--file-input', accessibility: 'Renders a native file input with browser picker, keyboard, form, multiple, capture, disabled, required, and invalid semantics.', extension: 'accept, multiple, capture, and native file selection remain caller-owned; it never uploads, reads, or stores files.', ...sharedEvidence },
    { name: 'Avatar', kind: 'component', status: 'stable', styles: ['gluon-atom-avatar'], variants: ['image', 'initials', 'fallback'], states: ['loading', 'loaded', 'error'], preview: 'avatar', accessibility: 'Loaded state renders one native img with meaningful alt; loading/error/no-src render one named fallback image without duplicate announcements.', extension: 'attributes targets the loaded HTMLImageElement; src, alt, fallback, and lifecycle status stay caller-owned with no account, fetch, upload, or CDN ownership.', ...sharedEvidence },
    { name: 'Button', kind: 'component', status: 'stable', styles: ['gluon-atom-button'], variants: ['primary', 'secondary', 'ghost'], states: ['default', 'disabled', 'loading'], preview: 'button', accessibility: 'Renders a native type=button control, preserves disabled semantics, and exposes a visible focus indicator with a 44px minimum target.', extension: 'attributes targets HTMLButtonElement; children, type, and disabled stay explicit; defineButtonPreset owns app presets.', ...sharedEvidence },
    { name: 'Checkbox', kind: 'component', status: 'stable', styles: ['gluon-atom-checkbox'], variants: ['default', 'indeterminate'], states: ['unchecked', 'checked', 'disabled', 'invalid'], preview: 'checkbox', accessibility: 'Renders a native checkbox with Space-key, label, form, required, disabled, checked, indeterminate, forced-colors, and visible-focus semantics.', extension: 'attributes targets HTMLInputElement; type, checked, indeterminate, validation, name, value, required, and disabled stay explicit.', ...sharedEvidence },
    { name: 'Icon', kind: 'component', status: 'stable', styles: ['gluon-atom-icon'], variants: ['decorative', 'informative'], states: ['default'], preview: 'icon', accessibility: 'Decorative icons are aria-hidden; informative icons require a label and expose role=img.', extension: 'attributes targets SVGSVGElement; role, naming, size, and body stay explicit; defineIcon owns custom geometry.', ...sharedEvidence },
    { name: 'Input', kind: 'component', status: 'stable', styles: ['gluon-atom-input'], variants: ['text', 'email', 'search'], states: ['default', 'disabled', 'invalid'], preview: 'input', accessibility: 'Renders a native input; callers associate it with Label or FormField and may expose aria-invalid.', extension: 'attributes targets HTMLInputElement; value, validation, type, name, placeholder, and disabled stay explicit.', ...sharedEvidence },
    { name: 'Label', kind: 'component', status: 'stable', styles: ['gluon-atom-label'], variants: ['default', 'required', 'optional'], states: ['default'], preview: 'label', accessibility: 'Provides visible label text and is composed inside a native label by FormField.', extension: 'attributes targets HTMLSpanElement; visible children stay explicit.', ...sharedEvidence },
    { name: 'Progress', kind: 'component', status: 'stable', styles: ['gluon-atom-progress'], variants: ['determinate', 'indeterminate'], states: ['default'], preview: 'progress', accessibility: 'Renders a native progress element; determinate values expose value/max while indeterminate state omits value, and callers provide an accessible name.', extension: 'attributes targets HTMLProgressElement; value, max, and full-width presentation stay explicit.', ...sharedEvidence },
    { name: 'Radio', kind: 'component', status: 'stable', styles: ['gluon-atom-radio'], variants: ['default'], states: ['unchecked', 'checked', 'disabled', 'invalid'], preview: 'radio', accessibility: 'Renders a native radio with same-name grouping, Arrow/Space keyboard, label, form, required, disabled, checked, forced-colors, and visible-focus semantics.', extension: 'attributes targets HTMLInputElement; type, checked, validation, name, value, required, and disabled stay explicit; callers or ChoiceGroup own the accessible group label.', ...sharedEvidence },
    { name: 'Select', kind: 'component', status: 'stable', styles: ['gluon-atom-select'], variants: ['default', 'compact'], states: ['default', 'disabled', 'invalid'], preview: 'select', accessibility: 'Renders a native select with platform keyboard and option semantics, a 44px minimum target, visible focus, and explicit invalid state.', extension: 'attributes targets HTMLSelectElement; children, value, validation, size, name, required, and disabled stay explicit.', ...sharedEvidence },
    { name: 'Slider', kind: 'component', status: 'stable', styles: ['gluon-atom-slider'], variants: ['horizontal', 'vertical'], states: ['default', 'disabled'], preview: 'slider', accessibility: 'Renders a native range input with normalized min/max/step, orientation, keyboard and pointer input, RTL, disabled/readonly, value text, 44px target, forced-colors, and zoom-safe semantics; it defines no animation.', extension: 'attributes targets HTMLInputElement; controlled value and uncontrolled defaultValue are exclusive, while orientation, readonly, valueText, and native input/change callbacks stay explicit.', ...sharedEvidence },
    { name: 'StatusBadge', kind: 'component', status: 'stable', styles: ['gluon-atom-status-badge'], variants: ['neutral', 'success', 'warning', 'danger'], states: ['default'], preview: 'badge', accessibility: 'Renders a presentational span with one-line short labels, bounded long tokens, zoom, RTL, contrast, and forced-colors support; callers own visible status text and any live-region semantics.', extension: 'attributes targets HTMLSpanElement; children and neutral, info, success, warning, or danger presentation stay explicit while domain mapping remains application-owned. Use app-owned multiline styling only when a product deliberately needs it.', ...sharedEvidence },
    { name: 'ScrollArea', kind: 'component', status: 'stable', styles: ['gluon-atom-scroll-area'], variants: ['vertical', 'horizontal', 'both'], states: ['default', 'overflow'], preview: 'scroll-area', accessibility: 'Renders a named native section region with native overflow, caller-overridable tabIndex, visible focus, forced-colors focus, and reduced-motion scroll-behavior enforcement.', extension: 'attributes targets HTMLElement; orientation is vertical, horizontal, or both; --gluon-scroll-area-max-inline-size, --gluon-scroll-area-max-block-size, and --gluon-scroll-area-scroll-behavior own bounded presentation without custom scrollbar or virtualization state.', ...sharedEvidence },
    { name: 'Separator', kind: 'component', status: 'stable', styles: ['gluon-atom-separator'], variants: ['horizontal', 'vertical'], states: ['default'], preview: 'separator', accessibility: 'Renders a native hr with implicit horizontal separator semantics, explicit vertical orientation, or presentation/aria-hidden semantics when decorative.', extension: 'attributes targets HTMLHRElement; logical sizing uses --gluon-separator-length and --gluon-separator-thickness while caller classes/styles merge safely.', ...sharedEvidence },
    { name: 'Switch', kind: 'component', status: 'stable', styles: ['gluon-atom-switch'], variants: ['default'], states: ['off', 'on', 'disabled'], preview: 'switch', accessibility: 'Renders a native checkbox with role=switch, Space-key, label, form, required, disabled, checked, forced-colors, reduced-motion, RTL, and visible-focus semantics.', extension: 'attributes targets HTMLInputElement; type, role, checked, name, value, required, and disabled stay explicit; callers own a stable accessible label.', ...sharedEvidence },
    { name: 'Textarea', kind: 'component', status: 'stable', styles: ['gluon-atom-textarea'], variants: ['default'], states: ['default', 'disabled', 'invalid'], preview: 'textarea', accessibility: 'Renders a native multiline text control with editing, selection, form, disabled, readonly, required, invalid, and visible-focus semantics.', extension: 'attributes targets HTMLTextAreaElement; value, validation, rows, name, placeholder, readonly, required, and disabled stay explicit.', ...sharedEvidence },
    { name: 'ToggleButton', kind: 'component', status: 'stable', styles: ['gluon-atom-button', 'gluon-atom-toggle-button'], variants: ['default', 'ghost'], states: ['off', 'on', 'disabled'], preview: 'toggle-button', accessibility: 'Renders a native type=button control with required boolean aria-pressed, disabled semantics, visible focus, and a 44px minimum target.', extension: 'attributes targets HTMLButtonElement; pressed, type, and disabled stay explicit; defineToggleButtonPreset owns app presets.', ...sharedEvidence },
    { name: 'installUi', kind: 'stylesheet', status: 'stable', accessibility: 'One explicit target owner installs light or dark tokens, preserves visible focus and WCAG-aware contrast, and releases its exact stylesheet references.', extension: 'Target-scoped stylesheet owner only; it renders no native element and accepts no attributes or ref.', ...sharedEvidence },
  ]),
} as const satisfies UiPackageManifest);
