import type { UiPackageManifest } from '@gluonjs/quarks';

const sharedEvidence = {
  example: 'docs-site/examples/ui-system.ts',
  tests: ['tests/ui-system.spec.ts', 'tests/ui-visual.spec.ts'],
} as const;

export const atomManifest = Object.freeze({
  schemaVersion: 1,
  package: '@gluonjs/atoms',
  layer: 'atom',
  entries: Object.freeze([
    { name: 'AspectRatio', kind: 'component', status: 'stable', styles: ['gluon-atom-aspect-ratio'], accessibility: 'Renders a native div without adding semantics; positive finite ratio validation prevents invalid geometry.', extension: 'attributes targets HTMLDivElement; ratio maps to --gluon-aspect-ratio and caller classes/styles merge safely.', ...sharedEvidence },
    { name: 'Avatar', kind: 'component', status: 'stable', styles: ['gluon-atom-avatar'], accessibility: 'Loaded state renders one native img with meaningful alt; loading/error/no-src render one named fallback image without duplicate announcements.', extension: 'attributes targets the loaded HTMLImageElement; src, alt, fallback, and lifecycle status stay caller-owned with no account, fetch, upload, or CDN ownership.', ...sharedEvidence },
    { name: 'Button', kind: 'component', status: 'stable', styles: ['gluon-atom-button'], accessibility: 'Renders a native type=button control, preserves disabled semantics, and exposes a visible focus indicator with a 44px minimum target.', extension: 'attributes targets HTMLButtonElement; children, type, and disabled stay explicit; defineButtonPreset owns app presets.', ...sharedEvidence },
    { name: 'Checkbox', kind: 'component', status: 'stable', styles: ['gluon-atom-checkbox'], accessibility: 'Renders a native checkbox with Space-key, label, form, required, disabled, checked, indeterminate, forced-colors, and visible-focus semantics.', extension: 'attributes targets HTMLInputElement; type, checked, indeterminate, validation, name, value, required, and disabled stay explicit.', ...sharedEvidence },
    { name: 'Icon', kind: 'component', status: 'stable', styles: ['gluon-atom-icon'], accessibility: 'Decorative icons are aria-hidden; informative icons require a label and expose role=img.', extension: 'attributes targets SVGSVGElement; role, naming, size, and body stay explicit; defineIcon owns custom geometry.', ...sharedEvidence },
    { name: 'Input', kind: 'component', status: 'stable', styles: ['gluon-atom-input'], accessibility: 'Renders a native input; callers associate it with Label or FormField and may expose aria-invalid.', extension: 'attributes targets HTMLInputElement; value, validation, type, name, placeholder, and disabled stay explicit.', ...sharedEvidence },
    { name: 'Label', kind: 'component', status: 'stable', styles: ['gluon-atom-label'], accessibility: 'Provides visible label text and is composed inside a native label by FormField.', extension: 'attributes targets HTMLSpanElement; visible children stay explicit.', ...sharedEvidence },
    { name: 'Progress', kind: 'component', status: 'stable', styles: ['gluon-atom-progress'], accessibility: 'Renders a native progress element; determinate values expose value/max while indeterminate state omits value, and callers provide an accessible name.', extension: 'attributes targets HTMLProgressElement; value, max, and full-width presentation stay explicit.', ...sharedEvidence },
    { name: 'Radio', kind: 'component', status: 'stable', styles: ['gluon-atom-radio'], accessibility: 'Renders a native radio with same-name grouping, Arrow/Space keyboard, label, form, required, disabled, checked, forced-colors, and visible-focus semantics.', extension: 'attributes targets HTMLInputElement; type, checked, validation, name, value, required, and disabled stay explicit; callers or ChoiceGroup own the accessible group label.', ...sharedEvidence },
    { name: 'Select', kind: 'component', status: 'stable', styles: ['gluon-atom-select'], accessibility: 'Renders a native select with platform keyboard and option semantics, a 44px minimum target, visible focus, and explicit invalid state.', extension: 'attributes targets HTMLSelectElement; children, value, validation, size, name, required, and disabled stay explicit.', ...sharedEvidence },
    { name: 'Slider', kind: 'component', status: 'stable', styles: ['gluon-atom-slider'], accessibility: 'Renders a native range input with normalized min/max/step, orientation, keyboard and pointer input, RTL, disabled/readonly, value text, 44px target, forced-colors, and zoom-safe semantics; it defines no animation.', extension: 'attributes targets HTMLInputElement; controlled value and uncontrolled defaultValue are exclusive, while orientation, readonly, valueText, and native input/change callbacks stay explicit.', ...sharedEvidence },
    { name: 'StatusBadge', kind: 'component', status: 'stable', styles: ['gluon-atom-status-badge'], accessibility: 'Renders a presentational span with one-line short labels, bounded long tokens, zoom, RTL, contrast, and forced-colors support; callers own visible status text and any live-region semantics.', extension: 'attributes targets HTMLSpanElement; children and neutral, info, success, warning, or danger presentation stay explicit while domain mapping remains application-owned. Use app-owned multiline styling only when a product deliberately needs it.', ...sharedEvidence },
    { name: 'ScrollArea', kind: 'component', status: 'stable', styles: ['gluon-atom-scroll-area'], accessibility: 'Renders a named native section region with native overflow, caller-overridable tabIndex, visible focus, forced-colors focus, and reduced-motion scroll-behavior enforcement.', extension: 'attributes targets HTMLElement; orientation is vertical, horizontal, or both; --gluon-scroll-area-max-inline-size, --gluon-scroll-area-max-block-size, and --gluon-scroll-area-scroll-behavior own bounded presentation without custom scrollbar or virtualization state.', ...sharedEvidence },
    { name: 'Separator', kind: 'component', status: 'stable', styles: ['gluon-atom-separator'], accessibility: 'Renders a native hr with implicit horizontal separator semantics, explicit vertical orientation, or presentation/aria-hidden semantics when decorative.', extension: 'attributes targets HTMLHRElement; logical sizing uses --gluon-separator-length and --gluon-separator-thickness while caller classes/styles merge safely.', ...sharedEvidence },
    { name: 'Switch', kind: 'component', status: 'stable', styles: ['gluon-atom-switch'], accessibility: 'Renders a native checkbox with role=switch, Space-key, label, form, required, disabled, checked, forced-colors, reduced-motion, RTL, and visible-focus semantics.', extension: 'attributes targets HTMLInputElement; type, role, checked, name, value, required, and disabled stay explicit; callers own a stable accessible label.', ...sharedEvidence },
    { name: 'Textarea', kind: 'component', status: 'stable', styles: ['gluon-atom-textarea'], accessibility: 'Renders a native multiline text control with editing, selection, form, disabled, readonly, required, invalid, and visible-focus semantics.', extension: 'attributes targets HTMLTextAreaElement; value, validation, rows, name, placeholder, readonly, required, and disabled stay explicit.', ...sharedEvidence },
    { name: 'ToggleButton', kind: 'component', status: 'stable', styles: ['gluon-atom-button', 'gluon-atom-toggle-button'], accessibility: 'Renders a native type=button control with required boolean aria-pressed, disabled semantics, visible focus, and a 44px minimum target.', extension: 'attributes targets HTMLButtonElement; pressed, type, and disabled stay explicit; defineToggleButtonPreset owns app presets.', ...sharedEvidence },
    { name: 'installUi', kind: 'stylesheet', status: 'stable', accessibility: 'One explicit target owner installs light or dark tokens, preserves visible focus and WCAG-aware contrast, and releases its exact stylesheet references.', extension: 'Target-scoped stylesheet owner only; it renders no native element and accepts no attributes or ref.', ...sharedEvidence },
  ]),
} as const satisfies UiPackageManifest);
