import type { UiPackageManifest } from '@gluonjs/quarks';

const sharedEvidence = {
  example: 'docs-site/examples/ui-system.ts',
  tests: ['tests/ui-system.spec.ts', 'tests/ui-visual.spec.ts'],
} as const;

export const organismManifest = Object.freeze({
  schemaVersion: 1,
  package: '@gluonjs/organisms',
  layer: 'organism',
  entries: Object.freeze([
    { name: 'AppShell', kind: 'component', status: 'stable', styles: ['gluon-organism-app-shell'], variants: ['default','sidebar'], states: ['default','responsive'], preview: 'app-shell', accessibility: 'Provides header, nav, main, and footer landmarks; callers give the navigation an accessible name when more than one nav exists.', extension: 'attributes targets outer HTMLDivElement; landmark content remains explicit component input.', ...sharedEvidence },
    { name: 'AdminShell', kind: 'component', status: 'stable', styles: ['gluon-organism-admin-shell'], variants: ['sidebar','responsive'], states: ['default','stacked'], preview: 'admin-shell', accessibility: 'Renders semantic header, labelled administration navigation, main, and optional footer regions with responsive stacking, visible focus, forced-colors, and reduced-motion support.', extension: 'Header, sidebar content, main content, footer, routing, permissions, authorization, data loading, mutations, mobile toggle state, localization, and tenant identity remain caller-owned; region attributes and CSS variables support application-specific composition.', ...sharedEvidence },
    { name: 'DashboardShell', kind: 'component', status: 'stable', styles: ['gluon-organism-dashboard-shell'], variants: ['sidebar','utility','responsive'], states: ['default','mobile-closed','mobile-open'], preview: 'dashboard-shell', accessibility: 'Renders semantic header, labelled dashboard navigation, main workspace, optional utility region, and footer with controlled mobile navigation, visible focus, forced-colors, and reduced-motion support.', extension: 'Header, sidebar, widgets, utility content, footer, routing, permissions, data loading, filters, persistence, mobile state, localization, and tenant identity remain caller-owned; region attributes, parts, and CSS variables support tenant-safe composition.', ...sharedEvidence },
    { name: 'SettingsShell', kind: 'component', status: 'stable', styles: ['gluon-organism-settings-shell'], variants: ['navigation','responsive','mobile'], states: ['default','mobile-closed','mobile-open'], preview: 'settings-shell', accessibility: 'Renders semantic title, labelled settings navigation, main content, and optional footer with controlled mobile disclosure, Escape/focus return, 44px controls, visible focus, forced-colors, reduced-motion, and logical RTL-safe layout.', extension: 'Title, navigation, section content, active state, routing, permissions, authorization, data loading, persistence, save/reset actions, localization, analytics, tenant identity, and mutations remain caller-owned; region attributes, parts, and CSS variables support tenant-safe composition.', ...sharedEvidence },
    { name: 'AsyncState', kind: 'component', status: 'stable', styles: ['gluon-organism-async-state'], variants: ['loading','success','empty','error','partial'], states: ['loading','ready','degraded'], preview: 'async-state', accessibility: 'Renders a labelled section with one truthful state message, status or alert announcement only for transient feedback, and caller-owned content and recovery actions.', extension: 'Request-free and SSR-safe; callers own fetching, retry, authorization, routing, data, localization, and state transitions while id, attributes, parts, and CSS variables remain available for tenant-scoped styling.', ...sharedEvidence },
    { name: 'ProductCard', kind: 'component', status: 'stable', styles: ['gluon-organism-product-card'], variants: ['linked','plain'], states: ['default','available','unavailable'], preview: 'product-card', accessibility: 'Renders one native article with a heading, optional native destination, caller-owned media, price, availability, and action regions; no state is conveyed by color alone.', extension: 'Product identity and visible copy are typed input; price, inventory, payment, analytics, routing, and mutations remain caller-owned while data-product-id, parts, attributes, and CSS variables support tenant-scoped styling.', ...sharedEvidence },
    { name: 'ProductGallery', kind: 'component', status: 'stable', styles: ['gluon-organism-product-gallery'], variants: ['primary','responsive','cropped'], states: ['default','focusable','scrollable'], preview: 'product-gallery', accessibility: 'Renders a labelled figure collection with source-order-preserving primary media, meaningful alt text, decorative-image support, per-image identifiers, keyboard focus visibility, responsive scroll snapping, forced-colors, and reduced-motion support.', extension: 'Image URLs, alt text, crop treatment, selection state, lightbox, zoom, thumbnails, inventory, routing, analytics, localization, tenant media, and CSS variables remain caller-owned; stable root and image IDs support integration and tenant-specific styling.', ...sharedEvidence },
    { name: 'ProductGrid', kind: 'component', status: 'stable', styles: ['gluon-organism-product-grid'], variants: ['one','two','three','four'], states: ['empty','populated'], preview: 'product-grid', accessibility: 'Renders a responsive section and ordered source-preserving card list, with explicit caller-owned empty content and a predictable one-column small-screen fallback.', extension: 'Items, card rendering, empty copy, columns, sorting, filtering, pagination, virtualization, loading, authorization, and mutations remain caller-owned; data-columns and CSS variables are available for tenant-specific layout.', ...sharedEvidence },
    { name: 'ConfirmationDialog', kind: 'component', status: 'stable', styles: ['gluon-organism-confirmation-dialog'], variants: ['info','destructive'], states: ['closed','open','busy'], preview: 'confirmation-dialog', accessibility: 'Native modal dialog with stable title/description relationships, optional initial focus, native Escape/cancel/close behavior, focus restoration, inert busy/disabled actions, opt-in backdrop dismissal, and one polite status.', extension: 'attributes target the native HTMLDialogElement and expose native events; the optional controller owns only showModal/close/focus lifecycle while callers own action controls, copy, mutation, routing, and controlled state.', ...sharedEvidence },
    { name: 'WorkflowTimeline', kind: 'component', status: 'stable', styles: ['gluon-organism-workflow-timeline'], variants: ['active','blocked','complete'], states: ['pending','active','complete'], preview: 'workflow', accessibility: 'Renders one ordered list with a truthful localized overall summary, instance-namespaced relationships, aria-current="step" for at most one current stage, and explicit localized status, role, evidence, and action/link content.', extension: 'Request-free and SSR-safe; a stable root id is required, omitted overall state derives as empty/active/blocked/complete, invalid input fails closed, attributes target the outer section, and steps accept native TemplateValue slots.', ...sharedEvidence },
    { name: 'MegaMenu', kind: 'component', status: 'stable', styles: ['gluon-organism-mega-menu'], variants: ['grouped','responsive','keyboard'], states: ['closed','open','active','disabled'], preview: 'mega-menu', accessibility: 'Renders a labelled native navigation with grouped links, controlled disclosure, Escape/focus return, Arrow/Home/End keyboard traversal, disabled-link semantics, mobile stacking, and forced-colors/reduced-motion support.', extension: 'Groups, labels, URLs, active state, authorization, routing, analytics, localization, global shortcuts, and tenant-specific CSS variables remain caller-owned.', ...sharedEvidence },
    { name: 'SiteHeader', kind: 'component', status: 'stable', styles: ['gluon-organism-site-header'], variants: ['brand','navigation','actions','mobile'], states: ['default','mobile-closed','mobile-open'], preview: 'site-header', accessibility: 'Renders a semantic header with optional labelled primary navigation, caller-owned brand/actions, controlled mobile disclosure, Escape/focus return, 44px controls, and reduced-motion/forced-colors support.', extension: 'Brand, navigation, actions, routing, authorization, localization, analytics, tenant identity, and mobile open state remain caller-owned; region attributes and CSS variables support application-specific composition.', ...sharedEvidence },
    { name: 'MarketingHeader', kind: 'component', status: 'stable', styles: ['gluon-organism-marketing-header'], variants: ['announcement','brand','navigation','actions','mobile'], states: ['default','mobile-closed','mobile-open'], preview: 'marketing-header', accessibility: 'Renders a semantic marketing header with optional announcement, labelled primary navigation, caller-owned brand/actions, controlled mobile disclosure, Escape/focus return, 44px controls, and reduced-motion/forced-colors support.', extension: 'Announcement, brand, navigation, actions, links, routing, authorization, localization, analytics, tenant identity, and mobile open state remain caller-owned; region attributes, parts, and CSS variables support campaign- and tenant-specific composition.', ...sharedEvidence },
    { name: 'SiteFooter', kind: 'component', status: 'stable', styles: ['gluon-organism-site-footer'], variants: ['brand','navigation','legal','meta'], states: ['default','stacked','compact'], preview: 'site-footer', accessibility: 'Renders a semantic footer with optional labelled navigation and caller-owned brand, legal, and metadata regions; responsive stacking, focus visibility, forced-colors, and reduced-motion support are provided by the exact stylesheet.', extension: 'Brand, navigation, legal copy, metadata, URLs, routing, authorization, localization, analytics, tenant identity, and content order remain caller-owned; region attributes and CSS variables support application-specific composition.', ...sharedEvidence },
    { name: 'PageLayout', kind: 'component', status: 'stable', styles: ['gluon-organism-page-layout'], variants: ['content','aside','responsive'], states: ['default','stacked'], preview: 'page-layout', accessibility: 'Renders a semantic header with a stable title, main content labelled by that title, optional labelled aside, and optional footer with responsive stacking and logical CSS.', extension: 'Title, breadcrumbs, actions, main/aside/footer content, routing, data, authorization, localization, tenant identity, and application state remain caller-owned; region attributes and CSS variables support tenant-safe composition.', ...sharedEvidence },
    { name: 'SplitPane', kind: 'component', status: 'stable', styles: ['gluon-organism-split-pane'], variants: ['horizontal','vertical','responsive'], states: ['expanded','collapsed','stacked'], preview: 'split-pane', accessibility: 'Renders labelled primary and secondary regions with a keyboard-operable native collapse control, responsive stacking, visible focus, forced-colors, and reduced-motion support.', extension: 'Primary and secondary content, orientation, collapse state, labels, routing, permissions, data loading, mutations, localization, tenant identity, and domain state remain caller-owned; region attributes and CSS variables support tenant-safe composition.', ...sharedEvidence },
    { name: 'ResizablePanels', kind: 'component', status: 'stable', styles: ['gluon-organism-resizable-panels'], variants: ['horizontal','vertical','responsive'], states: ['expanded','collapsed','resizable'], preview: 'resizable-panels', accessibility: 'Renders two or more labelled panel regions with keyboard-operable native separator semantics, bounded size values, controlled collapse buttons, responsive stacking, visible focus, forced-colors, and reduced-motion support.', extension: 'Panel content, sizes, persistence, pointer/drag policy, routing, permissions, data loading, mutations, localization, and tenant identity remain caller-owned; stable IDs, parts, panel attributes, and CSS variables support application-specific composition.', ...sharedEvidence },
    { name: 'NavigationRail', kind: 'component', status: 'stable', styles: ['gluon-organism-navigation-rail'], variants: ['expanded','collapsed','mobile'], states: ['default','active','disabled','mobile-open'], preview: 'navigation-rail', accessibility: 'Renders a labelled navigation landmark with grouped links, active and disabled semantics, controlled desktop collapse, mobile disclosure, Escape/focus return, 44px controls, visible focus, forced-colors, and reduced-motion support.', extension: 'Groups, labels, URLs, active state, badges, routing, authorization, permissions, analytics, localization, tenant identity, and state persistence remain caller-owned; region attributes, parts, and CSS variables support application-specific composition.', ...sharedEvidence },
    { name: 'SidebarLayout', kind: 'component', status: 'stable', styles: ['gluon-organism-sidebar-layout'], variants: ['sidebar','responsive','mobile'], states: ['default','mobile-closed','mobile-open'], preview: 'sidebar-layout', accessibility: 'Renders semantic optional header/footer regions, a labelled sidebar navigation, and main content with controlled mobile disclosure, Escape/focus return, 44px controls, visible focus, forced-colors, and reduced-motion support.', extension: 'Header, sidebar content, main content, footer, routing, permissions, authorization, data loading, mobile state, localization, analytics, persistence, and tenant identity remain caller-owned; region attributes, parts, and CSS variables support tenant-safe composition.', ...sharedEvidence },
    { name: 'Wizard', kind: 'component', status: 'stable', styles: ['gluon-organism-wizard'], variants: ['linear','responsive','keyboard'], states: ['first','middle','last','invalid'], preview: 'wizard', accessibility: 'Renders a labelled step navigation with current-step semantics, keyboard-operable step and previous/next buttons, live progress, visible focus, 44px targets, forced-colors, and reduced-motion support.', extension: 'Steps, content, validation, routing, persistence, permissions, mutations, localization, analytics, and tenant identity remain caller-owned; controlled currentStep, callbacks, parts, native attributes, and CSS variables support tenant-safe workflows.', ...sharedEvidence },
    { name: 'OnboardingFlow', kind: 'component', status: 'stable', styles: ['gluon-organism-onboarding-flow'], variants: ['setup','responsive','completion'], states: ['first','middle','last','complete','invalid'], preview: 'onboarding-flow', accessibility: 'Renders a labelled first-run workflow with current-step semantics, keyboard-operable navigation, completion state, visible focus, 44px targets, forced-colors, and reduced-motion support.', extension: 'Steps, content, validation, routing, persistence, permissions, mutations, localization, analytics, and tenant identity remain caller-owned; controlled currentStep, completion state, callbacks, parts, native attributes, and CSS variables support tenant-safe workflows.', ...sharedEvidence },
    { name: 'ApprovalFlow', kind: 'component', status: 'stable', styles: ['gluon-organism-approval-flow'], variants: ['review','decision','evidence'], states: ['pending','in-review','approved','rejected','changes-requested','invalid'], preview: 'approval-flow', accessibility: 'Renders a labelled approval-stage navigation with current-stage semantics, truthful statuses, caller-owned evidence and actions, visible focus, 44px targets, forced-colors, and reduced-motion support.', extension: 'Stages, statuses, content, roles, evidence, actions, routing, permissions, authorization, localization, analytics, and mutations remain caller-owned; controlled currentStage, callbacks, parts, native attributes, and CSS variables support tenant-safe review workflows.', ...sharedEvidence },
    { name: 'StatusTracker', kind: 'component', status: 'stable', styles: ['gluon-organism-status-tracker'], variants: ['progress','history','actions'], states: ['pending','in-progress','success','warning','error','paused','invalid'], preview: 'status-tracker', accessibility: 'Renders a labelled status list with current-item semantics, truthful status text, native progress meters, timestamps, visible focus, 44px action targets, forced-colors, and reduced-motion support.', extension: 'Items, status transitions, timestamps, progress, actions, fetching, persistence, routing, permissions, mutations, localization, analytics, and tenant identity remain caller-owned; currentId, parts, native attributes, and CSS variables support tenant-safe tracking surfaces.', ...sharedEvidence },
    { name: 'NotificationCenter', kind: 'component', status: 'stable', styles: ['gluon-organism-notification-center'], variants: ['unread','grouped','actions'], states: ['closed','open','empty','invalid'], preview: 'notification-center', accessibility: 'Renders a labelled notification trigger and controlled region with unread count, read state, timestamps, keyboard-operable caller callbacks, visible focus, 44px action targets, forced-colors, and reduced-motion support.', extension: 'Notification records, fetching, persistence, routing, permissions, localization, authorization, and mutations remain caller-owned; controlled open state, item callbacks, parts, native attributes, and CSS variables support tenant-safe notification surfaces.', ...sharedEvidence },
  ]),
} as const satisfies UiPackageManifest);
