import type { UiPackageManifest } from '@gluonjs/quarks';

const sharedEvidence = {
  example: 'docs-site/examples/ui-system.ts',
  tests: ['tests/ui-system.spec.ts', 'tests/ui-visual.spec.ts'],
} as const;

export const organismManifest = Object.freeze({
  schemaVersion: 1,
  package: '@gluonjs/organisms',
  layer: 'organism',
  entries: Object.freeze([
    { name: 'AppShell', kind: 'component', status: 'stable', styles: ['gluon-organism-app-shell'], variants: ['default','sidebar'], states: ['default','responsive'], preview: 'app-shell', accessibility: 'Provides header, nav, main, and footer landmarks; callers give the navigation an accessible name when more than one nav exists.', extension: 'attributes targets outer HTMLDivElement; landmark content remains explicit component input.', ...sharedEvidence },
    { name: 'AdminShell', kind: 'component', status: 'stable', styles: ['gluon-organism-admin-shell'], variants: ['sidebar','responsive'], states: ['default','stacked'], preview: 'admin-shell', accessibility: 'Renders semantic header, labelled administration navigation, main, and optional footer regions with responsive stacking, visible focus, forced-colors, and reduced-motion support.', extension: 'Header, sidebar content, main content, footer, routing, permissions, authorization, data loading, mutations, mobile toggle state, localization, and tenant identity remain caller-owned; region attributes and CSS variables support application-specific composition.', ...sharedEvidence },
    { name: 'AsyncState', kind: 'component', status: 'stable', styles: ['gluon-organism-async-state'], variants: ['loading','success','empty','error','partial'], states: ['loading','ready','degraded'], preview: 'async-state', accessibility: 'Renders a labelled section with one truthful state message, status or alert announcement only for transient feedback, and caller-owned content and recovery actions.', extension: 'Request-free and SSR-safe; callers own fetching, retry, authorization, routing, data, localization, and state transitions while id, attributes, parts, and CSS variables remain available for tenant-scoped styling.', ...sharedEvidence },
    { name: 'ProductCard', kind: 'component', status: 'stable', styles: ['gluon-organism-product-card'], variants: ['linked','plain'], states: ['default','available','unavailable'], preview: 'product-card', accessibility: 'Renders one native article with a heading, optional native destination, caller-owned media, price, availability, and action regions; no state is conveyed by color alone.', extension: 'Product identity and visible copy are typed input; price, inventory, payment, analytics, routing, and mutations remain caller-owned while data-product-id, parts, attributes, and CSS variables support tenant-scoped styling.', ...sharedEvidence },
    { name: 'ProductGrid', kind: 'component', status: 'stable', styles: ['gluon-organism-product-grid'], variants: ['one','two','three','four'], states: ['empty','populated'], preview: 'product-grid', accessibility: 'Renders a responsive section and ordered source-preserving card list, with explicit caller-owned empty content and a predictable one-column small-screen fallback.', extension: 'Items, card rendering, empty copy, columns, sorting, filtering, pagination, virtualization, loading, authorization, and mutations remain caller-owned; data-columns and CSS variables are available for tenant-specific layout.', ...sharedEvidence },
    { name: 'ConfirmationDialog', kind: 'component', status: 'stable', styles: ['gluon-organism-confirmation-dialog'], variants: ['info','destructive'], states: ['closed','open','busy'], preview: 'confirmation-dialog', accessibility: 'Native modal dialog with stable title/description relationships, optional initial focus, native Escape/cancel/close behavior, focus restoration, inert busy/disabled actions, opt-in backdrop dismissal, and one polite status.', extension: 'attributes target the native HTMLDialogElement and expose native events; the optional controller owns only showModal/close/focus lifecycle while callers own action controls, copy, mutation, routing, and controlled state.', ...sharedEvidence },
    { name: 'WorkflowTimeline', kind: 'component', status: 'stable', styles: ['gluon-organism-workflow-timeline'], variants: ['active','blocked','complete'], states: ['pending','active','complete'], preview: 'workflow', accessibility: 'Renders one ordered list with a truthful localized overall summary, instance-namespaced relationships, aria-current="step" for at most one current stage, and explicit localized status, role, evidence, and action/link content.', extension: 'Request-free and SSR-safe; a stable root id is required, omitted overall state derives as empty/active/blocked/complete, invalid input fails closed, attributes target the outer section, and steps accept native TemplateValue slots.', ...sharedEvidence },
    { name: 'MegaMenu', kind: 'component', status: 'stable', styles: ['gluon-organism-mega-menu'], variants: ['grouped','responsive','keyboard'], states: ['closed','open','active','disabled'], preview: 'mega-menu', accessibility: 'Renders a labelled native navigation with grouped links, controlled disclosure, Escape/focus return, Arrow/Home/End keyboard traversal, disabled-link semantics, mobile stacking, and forced-colors/reduced-motion support.', extension: 'Groups, labels, URLs, active state, authorization, routing, analytics, localization, global shortcuts, and tenant-specific CSS variables remain caller-owned.', ...sharedEvidence },
    { name: 'SiteHeader', kind: 'component', status: 'stable', styles: ['gluon-organism-site-header'], variants: ['brand','navigation','actions','mobile'], states: ['default','mobile-closed','mobile-open'], preview: 'site-header', accessibility: 'Renders a semantic header with optional labelled primary navigation, caller-owned brand/actions, controlled mobile disclosure, Escape/focus return, 44px controls, and reduced-motion/forced-colors support.', extension: 'Brand, navigation, actions, routing, authorization, localization, analytics, tenant identity, and mobile open state remain caller-owned; region attributes and CSS variables support application-specific composition.', ...sharedEvidence },
    { name: 'SiteFooter', kind: 'component', status: 'stable', styles: ['gluon-organism-site-footer'], variants: ['brand','navigation','legal','meta'], states: ['default','stacked','compact'], preview: 'site-footer', accessibility: 'Renders a semantic footer with optional labelled navigation and caller-owned brand, legal, and metadata regions; responsive stacking, focus visibility, forced-colors, and reduced-motion support are provided by the exact stylesheet.', extension: 'Brand, navigation, legal copy, metadata, URLs, routing, authorization, localization, analytics, tenant identity, and content order remain caller-owned; region attributes and CSS variables support application-specific composition.', ...sharedEvidence },
  ]),
} as const satisfies UiPackageManifest);
